# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy 

on:
  push:
    branches: [ "main" ]

jobs:
  dependencies:
    name: Build 
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      USERNAME: warioddly
      EMAIL: ${{ secrets.EMAIL }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: 'stable'
          cache: true
    
      - name: Run Flutter build
        run: |
          # Enable web config in flutter
          flutter config --enable-web
          
          # Get project dependencies
          flutter pub get
          
          # Build project
          flutter build web --release --web-renderer=canvaskit --base-href="/dungeon/"

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
