# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Portfolio

on:
  push:
    branches: [ "main" ]

jobs:
  dependencies:
    name: Build Portfolio
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.TOKEN }}
      USERNAME: warioddly
      EMAIL: ${{ secrets.EMAIL }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: 'stable'
          cache: true // 2
    
      - name: "Run Flutter build"
        run: |
          # Enable web config in flutter
          flutter config --enable-web
          
          # Get project dependencies
          flutter pub get
          
          # Build project
          flutter build web --release
        
      - name: "Deploy to Github Pages" 
        run: |
          cd build/web
          git init
          git config --global user.email ${{ env.EMAIL }}
          git config --global user.name ${{ env.USERNAME }}
          git config --global init.defaultBranch main
          git remote add origin https://oauth2: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@github.com/warioddly/portfolio.git
          git checkout -b gh-pages
          git add .
          git commit -m "update"
          git status
          git push origin gh-pages -f
